### ISSUE TITLE
Check functionality of breaking/splitting  closed road (was: Segfault after split)

### ISSUE THREAD

**Issue by tomhughes** [tomhughes/trac-tickets#1063]
**[Submitted to the original trac issue database at 9.01am, Thursday, 24th July 2008]**

(Reported to the mailinglist by Tom Mika)

Hi all: Here is issue with split road in my compilation on Ubuntu
8.04, merkaartor , release rev. 9269 Recreation: new screen, create
road, like triangle (end point is in the beggin point ) , click to
node (your choice) with right mouse button and select split. Crash...

**Comment by tomhughes** [comment]
**Author: killefiz**
**[Added to the original trac issue at 9.07am, Thursday, 24th July 2008]**

Backtrace:

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fee763d3780 (LWP 8050)]
0x0000000000443c76 in MapDocument::getDirtyOrOriginLayer (this=0x9674c0, aLayer=0x0) at Map/MapDocument.cpp:413
413             if (aLayer->isUploadable())
(gdb) bt
#0  0x0000000000443c76 in MapDocument::getDirtyOrOriginLayer (this=0x9674c0, aLayer=0x0) at Map/MapDocument.cpp:413
#1  0x0000000000475e50 in splitRoad (theDocument=0x9674c0, theList=0x9daeb0, In=0x9fa1a0, Points=@0x7fff7e3fb420, Result=@0x7fff7e3fb440)
    at Map/RoadManipulations.cpp:150
#2  0x00000000004763a6 in splitRoads (theDocument=0x9674c0, theList=0x9daeb0, theDock=0x97c960) at Map/RoadManipulations.cpp:213
#3  0x00000000004c1cec in MainWindow::on_roadSplitAction_triggered (this=0x7fff7e3fe2e0) at MainWindow.cpp:755
#4  0x00000000005314ef in MainWindow::qt_metacall (this=0x7fff7e3fe2e0, _c=QMetaObject::InvokeMetaMethod, _id=41, _a=0x7fff7e3fb630)
    at tmp/moc_MainWindow.cpp:244
#5  0x00007fee741e0286 in QMetaObject::activate () from /usr/lib/libQtCore.so.4
#6  0x00007fee7498afa7 in QAction::triggered () from /usr/lib/libQtGui.so.4
#7  0x00007fee7498b7b0 in QAction::activate () from /usr/lib/libQtGui.so.4
#8  0x00007fee74d20caa in ?? () from /usr/lib/libQtGui.so.4
#9  0x00007fee749df4e0 in QWidget::event () from /usr/lib/libQtGui.so.4
#10 0x00007fee74d1ea21 in QMenu::event () from /usr/lib/libQtGui.so.4
#11 0x00007fee7499154f in QApplicationPrivate::notify_helper () from /usr/lib/libQtGui.so.4
#12 0x00007fee74996329 in QApplication::notify () from /usr/lib/libQtGui.so.4
#13 0x00007fee741cc109 in QCoreApplication::notifyInternal () from /usr/lib/libQtCore.so.4
#14 0x00007fee74993455 in QApplicationPrivate::sendMouseEvent () from /usr/lib/libQtGui.so.4
#15 0x00007fee749f591b in ?? () from /usr/lib/libQtGui.so.4
#16 0x00007fee749f466b in QApplication::x11ProcessEvent () from /usr/lib/libQtGui.so.4
#17 0x00007fee74a1a8f3 in ?? () from /usr/lib/libQtGui.so.4
#18 0x00007fee723f83d4 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#19 0x00007fee723fb6e5 in ?? () from /usr/lib/libglib-2.0.so.0
#20 0x00007fee723fbbcb in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#21 0x00007fee741f53af in QEventDispatcherGlib::processEvents () from /usr/lib/libQtCore.so.4
#22 0x00007fee74a1a72f in ?? () from /usr/lib/libQtGui.so.4
#23 0x00007fee741cb585 in QEventLoop::processEvents () from /usr/lib/libQtCore.so.4
#24 0x00007fee741cb6db in QEventLoop::exec () from /usr/lib/libQtCore.so.4
#25 0x00007fee74d230e5 in QMenu::exec () from /usr/lib/libQtGui.so.4
#26 0x000000000047fdda in MapView::on_customContextMenuRequested (this=0x8f3490, pos=@0x7fff7e3fd658) at MapView.cpp:461
#27 0x00000000005323f6 in MapView::qt_metacall (this=0x8f3490, _c=QMetaObject::InvokeMetaMethod, _id=4, _a=0x7fff7e3fced0)
    at tmp/moc_MapView.cpp:75
#28 0x00007fee741e0286 in QMetaObject::activate () from /usr/lib/libQtCore.so.4
#29 0x000000000052fe3f in Interaction::requestCustomContextMenu (this=0x9d1120, _t1=@0x7fff7e3fd658) at tmp/moc_Interaction.cpp:76
#30 0x0000000000495607 in Interaction::mouseReleaseEvent (this=0x9d1120, anEvent=0x7fff7e3fd640) at Interaction/Interaction.cpp:74
#31 0x00000000004882bc in GenericFeatureSnapInteraction<MapFeature>::mouseReleaseEvent (this=0x9d1120, event=0x7fff7e3fd640)
    at ./Interaction/Interaction.h:88
#32 0x000000000047f01a in MapView::mouseReleaseEvent (this=0x8f3490, event=0x7fff7e3fd640) at MapView.cpp:357
#33 0x00007fee749df4e0 in QWidget::event () from /usr/lib/libQtGui.so.4
#34 0x00007fee7499154f in QApplicationPrivate::notify_helper () from /usr/lib/libQtGui.so.4
#35 0x00007fee74996329 in QApplication::notify () from /usr/lib/libQtGui.so.4
#36 0x00007fee741cc109 in QCoreApplication::notifyInternal () from /usr/lib/libQtCore.so.4
#37 0x00007fee74993455 in QApplicationPrivate::sendMouseEvent () from /usr/lib/libQtGui.so.4
#38 0x00007fee749f5756 in ?? () from /usr/lib/libQtGui.so.4
#39 0x00007fee749f466b in QApplication::x11ProcessEvent () from /usr/lib/libQtGui.so.4
#40 0x00007fee74a1a8f3 in ?? () from /usr/lib/libQtGui.so.4
#41 0x00007fee723f83d4 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#42 0x00007fee723fb6e5 in ?? () from /usr/lib/libglib-2.0.so.0
#43 0x00007fee723fbbcb in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#44 0x00007fee741f53af in QEventDispatcherGlib::processEvents () from /usr/lib/libQtCore.so.4
#45 0x00007fee74a1a72f in ?? () from /usr/lib/libQtGui.so.4
#46 0x00007fee741cb585 in QEventLoop::processEvents () from /usr/lib/libQtCore.so.4
#47 0x00007fee741cb6db in QEventLoop::exec () from /usr/lib/libQtCore.so.4
---Type <return> to continue, or q <return> to quit---
#48 0x00007fee741cd729 in QCoreApplication::exec () from /usr/lib/libQtCore.so.4
#49 0x00000000004bcc50 in main (argc=1, argv=0x7fff7e3fe838) at Main.cpp:51

**Comment by tomhughes** [comment]
**Author: koying**
**[Added to the original trac issue at 1.14pm, Thursday, 24th July 2008]**

(In [9276]) FIX : crash when splitting closed road. Functionality to reveiew after 0.11 (Refs #1063)
FIX : Cannot save an MDC after a failed load
FIX : OSM export was missing the first feature

**Comment by tomhughes** [comment]
**Author: koying**
**[Added to the original trac issue at 9.16am, Saturday, 26th July 2008]**

put to task due to crash solved
