### ISSUE TITLE
Crash when undoing selected way and then upload

### ISSUE THREAD

**Issue by tomhughes** [tomhughes/trac-tickets#1250]
**[Submitted to the original trac issue database at 9.30pm, Thursday, 9th October 2008]**

 * Draw a way with some nodes
 * Draw another way with several nodes
 * Select that second way
 * Undo all the nodes from the second way until the way vanishes
 * Upload

```
#0  0x000000000050498d in PropertiesDock::checkMenuStatus (this=0xc65ac0) at PropertiesDock.cpp:107
#1  0x00000000004ab6bf in EditInteraction (this=0xe9ccc0, theView=0x9563c0) at Interaction/EditInteraction.cpp:28
#2  0x00000000004ea609 in MainWindow::on_editPropertiesAction_triggered (this=0x7fffe38de740) at MainWindow.cpp:412
#3  0x00000000004e62be in MainWindow::on_fileUploadAction_triggered (this=0x7fffe38de740) at MainWindow.cpp:746
```

```
(gdb) p Selection.size()
$2 = 1
```

Some object is still selected, when it shouldn't.

**Comment by tomhughes** [comment]
**Author: dantje**
**[Added to the original trac issue at 11.33pm, Friday, 10th October 2008]**

Related crash:

 * Create two nodes
 * Select the second
 * Undo

```
(gdb) bt
#0  0x000000000045752e in MapLayer::name (this=0x0) at Map/MapLayer.cpp:151
#1  0x000000000048b5b9 in TrackPoint::toHtml (this=0xdd6af0) at Map/TrackPoint.cpp:364
#2  0x00000000005025d5 in PropertiesDock::resetValues (this=0xc55410) at PropertiesDock.cpp:384
#3  0x00000000004e9168 in MainWindow::invalidateView (this=0x7fff62dcfc30, UpdateDock=true)
    at MainWindow.cpp:237
#4  0x00000000004ea66e in MainWindow::on_editUndoAction_triggered (this=0x7fff62dcfc30)
    at MainWindow.cpp:405

```

**Comment by tomhughes** [comment]
**Author: dantje**
**[Added to the original trac issue at 12.27am, Saturday, 11th October 2008]**

Fixed in r11118
