### ISSUE TITLE
Merkaartor crashes downloading special area

### ISSUE THREAD

**Issue by tomhughes** [tomhughes/trac-tickets#2080]
**[Submitted to the original trac issue database at 7.16am, Monday, 20th July 2009]**

Every time I try to download the tiles in this area, merkaartor (013.2) and 0.14pre2 close after downloading:
Downloader::go:  "/api/0.6/map?bbox=11.742107,47.869553,11.778987,47.900998" 

The debug-box/file shows thousands of this notEverythingDownloaded, then the software crash down:

Thread 1 (thread 2644.0xcf0):
#0  0x006d7577 in __cxxabiv1::__si_class_type_info::__do_dyncast ()
No locals.
#1  0x006d75fd in __cxxabiv1::__si_class_type_info::__do_dyncast ()
No locals.
#2  0x006d7e94 in __dynamic_cast ()
No locals.
#3  0x00485557 in MapFeature::lastUpdated (this=0xac7e7c8) at Maps/MapFeature.cpp:185
No locals.
#4  0x0049bb5b in Relation::notEverythingDownloaded (this=0xac7e7c8) at Maps/Relation.cpp:302
	i = 2
#5  0x0049bbcb in Relation::notEverythingDownloaded (this=0xac7e7c8) at Maps/Relation.cpp:306
	i = 0
#6  0x0049bbcb in Relation::notEverythingDownloaded (this=0xac7e7c8) at Maps/Relation.cpp:306
	i = 0
#7  0x0049bbcb in Relation::notEverythingDownloaded (this=0xac7e7c8) at Maps/Relation.cpp:306
	i = 0
#8  0x0049bbcb in Relation::notEverythingDownloaded (this=0xac7e7c8) at Maps/Relation.cpp:306
	i = 0
#9  0x0049bbcb in Relation::notEverythingDownloaded (this=0xac7e7c8) at Maps/Relation.cpp:306
	i = 0
#10 0x0049bbcb in Relation::notEverythingDownloaded (this=0xac7e7c8) at Maps/Relation.cpp:306
	i = 0
#11 0x0049bbcb in Relation::notEverythingDownloaded (this=0xac7e7c8) at Maps/Relation.cpp:306
	i = 0
#12 0x0049bbcb in Relation::notEverythingDownloaded (this=0xac7e7c8) at Maps/Relation.cpp:306
	i = 0
#13 0x0049bbcb in Relation::notEverythingDownloaded (this=0xac7e7c8) at Maps/Relation.cpp:306
	i = 0
#14 0x0049bbcb in Relation::notEverythingDownloaded (this=0xac7e7c8) at Maps/Relation.cpp:306
	i = 0
#15 0x0049bbcb in Relation::notEverythingDownloaded (this=0xac7e7c8) at Maps/Relation.cpp:306
	i = 0
#16 0x0049bbcb in Relation::notEverythingDownloaded (this=0xac7e7c8) at Maps/Relation.cpp:306
	i = 0
#17 0x0049bbcb in Relation::notEverythingDownloaded (this=0xac7e7c8) at Maps/Relation.cpp:306
	i = 0
#18 0x0049bbcb in Relation::notEverythingDownloaded (this=0xac7e7c8) at Maps/Relation.cpp:306
	i = 0
#19 0x0049bbcb in Relation::notEverythingDownloaded (this=0xac7e7c8) at Maps/Relation.cpp:306
	i = 0
#20 0x0049bbcb in Relation::notEverythingDownloaded (this=0xac7e7c8) at Maps/Relation.cpp:306
	i = 0
#21 0x0049bbcb in Relation::notEverythingDownloaded (this=0xac7e7c8) at Maps/Relation.cpp:306
	i = 0
#22 0x0049bbcb in Relation::notEverythingDownloaded (this=0xac7e7c8) at Maps/Relation.cpp:306
	i = 0
#23 0x0049bbcb in Relation::notEverythingDownloaded (this=0xac7e7c8) at Maps/Relation.cpp:306
	i = 0
....

**Comment by tomhughes** [comment]
**Author: Koying**
**[Added to the original trac issue at 9.28am, Monday, 20th July 2009]**

Funny... I found out about this **potential** problem (recursing relations) no later than last week...

**Comment by tomhughes** [comment]
**Author: koying**
**[Added to the original trac issue at 11.12am, Monday, 20th July 2009]**

(In [16597]) FIX : Avoid infinite loop with imbricated relations (fixes #2080)
