### ISSUE TITLE
merkaartor is unable to draw any content, crashes on predownloaded content after search

### ISSUE THREAD

**Issue by tomhughes** [tomhughes/trac-tickets#2202]
**[Submitted to the original trac issue database at 3.50am, Wednesday, 19th August 2009]**

For now I am unable to see anything in Merkaartor. I have no clue what I did wrong. The window sticks with 0,0,0,0 and nothing is able to move. This happened after a crash where I tried to change the projection of a big document.

I seem also consistently able to crash it in this state using a predownloaded document from xapi. And trying to search a tag in this document. The following crash report can be extracted from gdb.

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7f37db523740 (LWP 9637)]
0x00007f37d999f446 in QVector<QPointF>::realloc ()
   from /usr/lib/qt4/libQtGui.so.4
Current language:  auto; currently asm
(gdb) bt
#0  0x00007f37d999f446 in QVector<QPointF>::realloc ()
   from /usr/lib/qt4/libQtGui.so.4
#1  0x00007f37d99d488e in QVector<QPointF>::append ()
   from /usr/lib/qt4/libQtGui.so.4
#2  0x00007f37d99cf314 in QBezier::addToPolygon ()
   from /usr/lib/qt4/libQtGui.so.4
#3  0x00007f37d9a0d02b in QPainterPath::toSubpathPolygons ()
   from /usr/lib/qt4/libQtGui.so.4
#4  0x00007f37d9a0d84b in QPainterPath::toFillPolygons ()
   from /usr/lib/qt4/libQtGui.so.4
#5  0x00007f37d9a0e552 in QPainterPath::toFillPolygons ()
   from /usr/lib/qt4/libQtGui.so.4
#6  0x00007f37d9abea84 in QX11PaintEnginePrivate::fillPath ()
   from /usr/lib/qt4/libQtGui.so.4
#7  0x00007f37d9abf039 in QX11PaintEngine::drawPath ()
   from /usr/lib/qt4/libQtGui.so.4
#8  0x00007f37d9abaf83 in QX11PaintEngine::drawPoints ()
   from /usr/lib/qt4/libQtGui.so.4
#9  0x00007f37d9a0365d in QPainter::drawPoints ()
   from /usr/lib/qt4/libQtGui.so.4
warning: (Internal error: pc 0x591a5a in read in psymtab, but not in symtab.)

#10 0x0000000000591a5b in QPainter::drawPoints (this=warning: (Internal error: pc 0x591a5a in read in psymtab, but not in symtab.)

warning: (Internal error: pc 0x591a28 in read in psymtab, but not in symtab.)

warning: (Internal error: pc 0x591a5a in read in psymtab, but not in symtab.)

0x7fffc51303a0, points=warning: (Internal error: pc 0x591a5a in read in psymtab, but not in symtab.)

@0x7fffc5130160) at /usr/include/qt4/QtGui/qpainter.h:646
#11 0x0000000000575bd8 in Road::drawFocus (this=0x7f37cc0aa7d0, 
    thePainter=@0x7fffc51303a0, theView=0x16f0710, solid=true)
    at Maps/Road.cpp:467
#12 0x00000000005b8003 in GenericFeatureSnapInteraction<MapFeature>::paintEvent
    (this=0x171a540, anEvent=0x7fffc5130bf0, thePainter=@0x7fffc51303a0)
    at ./Interaction/Interaction.h:91
#13 0x00000000005cff02 in EditInteraction::paintEvent (this=0x171a540, 
    anEvent=0x7fffc5130bf0, thePainter=@0x7fffc51303a0)
    at Interaction/EditInteraction.cpp:120
#14 0x00000000005ae0bb in MapView::paintEvent (this=0x16f0710, 
    anEvent=0x7fffc5130bf0) at MapView.cpp:210
#15 0x00007f37d9951507 in QWidget::event () from /usr/lib/qt4/libQtGui.so.4
#16 0x00000000005a82d8 in MapView::event (this=0x16f0710, event=0x7fffc5130bf0)
    at MapView.cpp:1172
#17 0x00007f37d9908f8d in QApplicationPrivate::notify_helper ()
   from /usr/lib/qt4/libQtGui.so.4
#18 0x00007f37d99107a2 in QApplication::notify ()
   from /usr/lib/qt4/libQtGui.so.4
#19 0x00007f37d791bf53 in QCoreApplication::notifyInternal ()
   from /usr/lib/qt4/libQtCore.so.4
#20 0x00007f37d9953e77 in QWidgetPrivate::drawWidget ()
   from /usr/lib/qt4/libQtGui.so.4
#21 0x00007f37d9accdb4 in QWidgetBackingStore::sync ()
   from /usr/lib/qt4/libQtGui.so.4
#22 0x00007f37d994729a in QWidgetPrivate::syncBackingStore ()
   from /usr/lib/qt4/libQtGui.so.4
#23 0x00007f37d995161d in QWidget::event () from /usr/lib/qt4/libQtGui.so.4
#24 0x00007f37d9c9951b in QMainWindow::event () from /usr/lib/qt4/libQtGui.so.4
#25 0x00007f37d9908f8d in QApplicationPrivate::notify_helper ()
   from /usr/lib/qt4/libQtGui.so.4
#26 0x00007f37d99107a2 in QApplication::notify ()
   from /usr/lib/qt4/libQtGui.so.4
#27 0x00007f37d791bf53 in QCoreApplication::notifyInternal ()
   from /usr/lib/qt4/libQtCore.so.4
#28 0x00007f37d791c83e in QCoreApplicationPrivate::sendPostedEvents ()
   from /usr/lib/qt4/libQtCore.so.4
#29 0x00007f37d793fd93 in postEventSourceDispatch ()
   from /usr/lib/qt4/libQtCore.so.4
#30 0x00007f37d7137771 in g_main_context_dispatch ()
   from /usr/lib/libglib-2.0.so.0
#31 0x00007f37d713ae28 in g_main_context_iterate ()
   from /usr/lib/libglib-2.0.so.0
#32 0x00007f37d713afec in g_main_context_iteration ()
   from /usr/lib/libglib-2.0.so.0
#33 0x00007f37d793fa3f in QEventDispatcherGlib::processEvents ()
   from /usr/lib/qt4/libQtCore.so.4
#34 0x00007f37d99892af in QGuiEventDispatcherGlib::processEvents ()
   from /usr/lib/qt4/libQtGui.so.4
#35 0x00007f37d791ab42 in QEventLoop::processEvents ()
   from /usr/lib/qt4/libQtCore.so.4
#36 0x00007f37d791acd5 in QEventLoop::exec () from /usr/lib/qt4/libQtCore.so.4
#37 0x00007f37d791ca96 in QCoreApplication::exec ()
   from /usr/lib/qt4/libQtCore.so.4
#38 0x0000000000613fe4 in main (argc=1, argv=0x7fffc5132718) at Main.cpp:204

**Comment by tomhughes** [comment]
**Author: stefan@konink.de**
**[Added to the original trac issue at 3.53am, Wednesday, 19th August 2009]**

It clearly seems to be preferences related. Because another user on the same system has no problems at all.

**Comment by tomhughes** [comment]
**Author: Koying**
**[Added to the original trac issue at 12.54pm, Tuesday, 15th September 2009]**

Doing a "View-Goto" to something should get you aout of 0, 0, 0, 0.

I'll see about the crash...

**Comment by tomhughes** [comment]
**Author: Koying**
**[Added to the original trac issue at 5.24pm, Monday, 24th May 2010]**

Too old. Assumed fixed
