### ISSUE TITLE
ruby traceback with search: Missing end tag for 'hr' (got "body")

### ISSUE THREAD

**Issue by tomhughes** [tomhughes/trac-tickets#2239]
**[Submitted to the original trac issue database at 4.42am, Sunday, 30th August 2009]**

I get a ruby traceback when I search on www.openstreetmap.org, from the namefinder:

Results from OpenStreetMap Namefinder

Error contacting gazetteer.openstreetmap.org: #> /usr/lib/ruby/1.8/rexml/parsers/baseparser.rb:320:in `pull' /usr/lib/ruby/1.8/rexml/parsers/treeparser.rb:21:in `parse' /usr/lib/ruby/1.8/rexml/document.rb:227:in `build' /usr/lib/ruby/1.8/rexml/document.rb:43:in `initialize' /home/rails/app/controllers/geocoder_controller.rb:325:in `new' /home/rails/app/controllers/geocoder_controller.rb:325:in `fetch_xml' /home/rails/app/controllers/geocoder_controller.rb:146:in `search_osm_namefinder' /var/lib/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/base.rb:1322:in `send' /var/lib/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/base.rb:1322:in `perform_action_without_filters' /var/lib/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/filters.rb:617:in `call_filters' /var/lib/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/filters.rb:610:in `perform_action_without_benchmark' /var/lib/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/benchmarking.rb:68:in `perform_action_without_rescue' /var/lib/gems/1.8/gems/activesupport-2.3.2/lib/active_support/core_ext/benchmark.rb:17:in `ms' /var/lib/gems/1.8/gems/activesupport-2.3.2/lib/active_support/core_ext/benchmark.rb:10:in `realtime' /var/lib/gems/1.8/gems/activesupport-2.3.2/lib/active_support/core_ext/benchmark.rb:17:in `ms' /var/lib/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/benchmarking.rb:68:in `perform_action_without_rescue' /var/lib/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/rescue.rb:160:in `perform_action_without_flash' /var/lib/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/flash.rb:141:in `perform_action' /var/lib/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/base.rb:523:in `send' /var/lib/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/base.rb:523:in `process_without_filters' /var/lib/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/filters.rb:606:in `process' /var/lib/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/base.rb:391:in `process' /var/lib/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/base.rb:386:in `call' /var/lib/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/routing/route_set.rb:433:in `call' /var/lib/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/dispatcher.rb:88:in `dispatch' /var/lib/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/dispatcher.rb:111:in `_call' /var/lib/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/dispatcher.rb:82:in `initialize' /var/lib/gems/1.8/gems/activerecord-2.3.2/lib/active_record/query_cache.rb:29:in `call' /var/lib/gems/1.8/gems/activerecord-2.3.2/lib/active_record/query_cache.rb:29:in `call' /var/lib/gems/1.8/gems/activerecord-2.3.2/lib/active_record/connection_adapters/abstract/query_cache.rb:34:in `cache' /var/lib/gems/1.8/gems/activerecord-2.3.2/lib/active_record/query_cache.rb:9:in `cache' /var/lib/gems/1.8/gems/activerecord-2.3.2/lib/active_record/query_cache.rb:28:in `call' /var/lib/gems/1.8/gems/activerecord-2.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:361:in `call' /var/lib/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/vendor/rack-1.0/rack/head.rb:9:in `call' /var/lib/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/vendor/rack-1.0/rack/methodoverride.rb:24:in `call' /var/lib/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/params_parser.rb:15:in `call' /var/lib/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/rewindable_input.rb:25:in `call' /var/lib/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/session/abstract_store.rb:122:in `call' /var/lib/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/failsafe.rb:11:in `call' /var/lib/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/vendor/rack-1.0/rack/lock.rb:11:in `call' /var/lib/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/vendor/rack-1.0/rack/lock.rb:11:in `synchronize' /var/lib/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/vendor/rack-1.0/rack/lock.rb:11:in `call' /var/lib/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/dispatcher.rb:106:in `call' /var/lib/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/vendor/rack-1.0/rack/content_length.rb:13:in `call' /var/lib/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/vendor/rack-1.0/rack/handler/fastcgi.rb:60:in `serve' /var/lib/gems/1.8/gems/rails-2.3.2/lib/fcgi_handler.rb:103:in `process_request' /var/lib/gems/1.8/gems/rails-2.3.2/lib/fcgi_handler.rb:153:in `with_signal_handler' /var/lib/gems/1.8/gems/rails-2.3.2/lib/fcgi_handler.rb:101:in `process_request' /home/rails/public/dispatch.fcgi:28:in `process_request' /var/lib/gems/1.8/gems/rails-2.3.2/lib/fcgi_handler.rb:78:in `process_each_request' /var/lib/gems/1.8/gems/rails-2.3.2/lib/fcgi_handler.rb:77:in `each' /var/lib/gems/1.8/gems/rails-2.3.2/lib/fcgi_handler.rb:77:in `process_each_request' /var/lib/gems/1.8/gems/rails-2.3.2/lib/fcgi_handler.rb:76:in `catch' /var/lib/gems/1.8/gems/rails-2.3.2/lib/fcgi_handler.rb:76:in `process_each_request' /var/lib/gems/1.8/gems/rails-2.3.2/lib/fcgi_handler.rb:51:in `process!' /var/lib/gems/1.8/gems/rails-2.3.2/lib/fcgi_handler.rb:23:in `process!' /home/rails/public/dispatch.fcgi:49 ... Missing end tag for 'hr' (got "body") Line: Position: Last 80 unconsumed characters: Line: Position: Last 80 unconsumed characters:

**Comment by tomhughes** [comment]
**Author: tom@compton.nu**
**[Added to the original trac issue at 8.23am, Sunday, 30th August 2009]**

Looks like the XML interface sent us back HTML for some reason?

**Comment by tomhughes** [comment]
**Author: iandees**
**[Added to the original trac issue at 10.47pm, Monday, 9th September 2013]**

Cleaning aging tickets.
