### ISSUE TITLE
osmosis SEVERE Execution aborted caused by null pointer

### ISSUE THREAD

**Issue by tomhughes** [tomhughes/trac-tickets#2486]
**[Submitted to the original trac issue database at 8.03pm, Saturday, 21st November 2009]**

any attempt to run with at least --rx cause:

21.11.2009 21:03:41 org.openstreetmap.osmosis.core.Osmosis main            21:07
SEVERE: Execution aborted.
java.lang.ExceptionInInitializerError
        at org.java.plugin.registry.xml.PluginRegistryImpl.configure(PluginRegis
tryImpl.java:108)
        at org.java.plugin.standard.StandardObjectFactory.createRegistry(Standar
dObjectFactory.java:98)
        at org.java.plugin.ObjectFactory.createManager(ObjectFactory.java:271)
        at org.openstreetmap.osmosis.core.TaskRegistrar.loadJPFPlugins(TaskRegis
trar.java:414)
        at org.openstreetmap.osmosis.core.TaskRegistrar.initialize(TaskRegistrar
.java:402)
        at org.openstreetmap.osmosis.core.Osmosis.run(Osmosis.java:74)
        at org.openstreetmap.osmosis.core.Osmosis.main(Osmosis.java:30)
Caused by: java.lang.NullPointerException
        at java.io.Reader.<init>(Unknown Source)
        at java.io.InputStreamReader.<init>(Unknown Source)
        at org.java.plugin.registry.xml.ManifestParser.loadPluginDtd(ManifestPar
ser.java:48)
        at org.java.plugin.registry.xml.ManifestParser.<clinit>(ManifestParser.j
ava:44)
        ... 7 more

tried on jre 1.6.0 update 17 both windows and linux64 versions

affected versions 0.31.2 0.31.3

version 0.31 on windows crashed with 

21.11.2009 21:17:12 org.openstreetmap.osmosis.core.Osmosis main
SEVERE: Execution aborted.
java.lang.NoClassDefFoundError: org/java/plugin/PluginLifecycleException
        at org.openstreetmap.osmosis.core.Osmosis.run(Osmosis.java:73)
        at org.openstreetmap.osmosis.core.Osmosis.main(Osmosis.java:30)
Caused by: java.lang.ClassNotFoundException: org.java.plugin.PluginLifecycleExce
ption
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClassInternal(Unknown Source)
        ... 2 more

**Comment by tomhughes** [comment]
**Author: woidrick**
**[Added to the original trac issue at 3.37pm, Sunday, 6th December 2009]**

upd: for some strange reason, osmosis start to work

only thing i remember i did change is a creation of /etc/osmosis

**Comment by tomhughes** [comment]
**Author: brett@bretth.com**
**[Added to the original trac issue at 6.45am, Sunday, 14th March 2010]**

I don't know why this defect wasn't closed, but as per the most recent comment Osmosis is working.
