### ISSUE TITLE
User Profile defect?

### ISSUE THREAD

**Issue by tomhughes** [tomhughes/trac-tickets#2488]
**[Submitted to the original trac issue database at 1.19pm, Sunday, 22nd November 2009]**

when I open my profile with http://www.openstreetmap.org/user/EM311 I got the following error message: 

Application error

The OpenStreetMap server encountered an unexpected condition that prevented it from fulfilling the request (HTTP 500)

Feel free to contact the OpenStreetMap community if your problem persists. Make a note of the exact URL / post data of your request.

This may be a problem in our Ruby On Rails code. 500 occurs with exceptions thrown outside of an action (like in Dispatcher setups or broken Ruby code)

Login into forums is also impossible. 

Last try was 22 Nov 2009 14:18 CET

**Comment by tomhughes** [comment]
**Author: tom@compton.nu**
**[Added to the original trac issue at 1.22pm, Sunday, 22nd November 2009]**

Log shows the following exception:

    ActionView::TemplateError (Numerical argument out of domain - asin) on line #132 of app/views/user/view.html.erb

with traceback:

    lib/osm.rb:330:in `asin'
    lib/osm.rb:330:in `bounds'
    app/models/user.rb:106:in `nearby'
    app/views/user/view.html.erb:132
    public/dispatch.fcgi:28:in `process_request'
    public/dispatch.fcgi:49

**Comment by tomhughes** [comment]
**Author: tom@compton.nu**
**[Added to the original trac issue at 1.22pm, Sunday, 22nd November 2009]**

Bah, let's try that again.... Traceback is:

```
    lib/osm.rb:330:in `asin'
    lib/osm.rb:330:in `bounds'
    app/models/user.rb:106:in `nearby'
    app/views/user/view.html.erb:132
    public/dispatch.fcgi:28:in `process_request'
    public/dispatch.fcgi:49
```

**Comment by tomhughes** [comment]
**[Added to the original trac issue at 1.35pm, Sunday, 22nd November 2009]**

(In [18736]) Catch domain exceptions as we approach the poles and handle them by
setting the longitude bounds to select a stripe right around the world
which is what they are tending to as we approach the poles.

Closes #2488.

**Comment by tomhughes** [comment]
**Author: tom@compton.nu**
**[Added to the original trac issue at 1.45pm, Sunday, 22nd November 2009]**

This fix has now been deployed - the underlying cause, and the reason it only affected you, was the fact that you had set your home location to the north pole.

**Comment by tomhughes** [comment]
**Author: EM311**
**[Added to the original trac issue at 2.45pm, Sunday, 22nd November 2009]**

Thanks, has bee fixed!
