### ISSUE TITLE
Segfault on upload button from editing name

### ISSUE THREAD

**Issue by tomhughes** [tomhughes/trac-tickets#2646]
**[Submitted to the original trac issue database at 10.13am, Thursday, 21st January 2010]**

I've created a lot of new features, and I want to use the name from one of them for my changeset comment.  So I pick one, and select the text in the Name field of the Properties dock.  Having done that, I then use the 'Upload' toolbar button and get this crash:

```
#0  0x00007ffff4288f55 in *__GI_raise (sig=<value optimized out>)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:64
#1  0x00007ffff428bd90 in *__GI_abort () at abort.c:88
#2  0x00000000006216e7 in myMessageOutput (msgType=QtFatalMsg, 
    buf=0x2587178 "ASSERT failure in QList<T>::operator[]: \"index out of range\", file /usr/include/qt4/QtCore/qlist.h, line 403") at Main.cpp:64
#3  0x00007ffff4fd36d3 in qt_message_output(QtMsgType, char const*) () from /usr/lib/libQtCore.so.4
#4  0x00007ffff4fd387b in qFatal(char const*, ...) () from /usr/lib/libQtCore.so.4
#5  0x000000000043c074 in QList<MapFeature*>::operator[] (this=0xe380c8, i=0)
    at /usr/include/qt4/QtCore/qlist.h:403
#6  0x0000000000435c6d in PropertiesDock::on_tag_changed (this=0xe38080, k=..., v=...)
    at Docks/PropertiesDock.cpp:639
#7  0x000000000072d346 in PropertiesDock::qt_metacall (this=0xe38080, 
    _c=QMetaObject::InvokeMetaMethod, _id=13, _a=0x7fffffff9ed0) at moc_PropertiesDock.cpp:109
#8  0x00007ffff50d5df2 in QMetaObject::activate(QObject*, int, int, void**) ()
   from /usr/lib/libQtCore.so.4
#9  0x00000000007356f9 in TagTemplates::tagChanged (this=0x10e53d0, _t1=..., _t2=...)
    at moc_TagTemplate.cpp:497
#10 0x000000000070c2e6 in TagTemplates::on_tag_changed (this=0x10e53d0, k=..., v=...)
    at TagTemplate/TagTemplate.cpp:1090
#11 0x0000000000735b0e in TagTemplates::qt_metacall (this=0x10e53d0, 
    _c=QMetaObject::InvokeMetaMethod, _id=5, _a=0x7fffffffa110) at moc_TagTemplate.cpp:478
#12 0x00007ffff50d5df2 in QMetaObject::activate(QObject*, int, int, void**) ()
   from /usr/lib/libQtCore.so.4
#13 0x0000000000735791 in TagTemplate::tagChanged (this=0x1126990, _t1=..., _t2=...)
    at moc_TagTemplate.cpp:413
#14 0x000000000070d50c in TagTemplate::on_tag_changed (this=0x1126990, k=..., v=...)
    at TagTemplate/TagTemplate.cpp:839
#15 0x00000000007362f0 in TagTemplate::qt_metacall (this=0x1126990, 
    _c=QMetaObject::InvokeMetaMethod, _id=3, _a=0x7fffffffa350) at moc_TagTemplate.cpp:394
#16 0x00007ffff50d5df2 in QMetaObject::activate(QObject*, int, int, void**) ()
   from /usr/lib/libQtCore.so.4
#17 0x0000000000735829 in TagTemplateWidget::tagChanged (this=0x10fb600, _t1=..., _t2=...)
    at moc_TagTemplate.cpp:88
#18 0x000000000070f3fb in TagTemplateWidgetEdit::on_editingFinished (this=0x10fb600)
    at TagTemplate/TagTemplate.cpp:655
#19 0x00000000007363e8 in TagTemplateWidgetEdit::qt_metacall (this=0x10fb600, 
    _c=QMetaObject::InvokeMetaMethod, _id=0, _a=0x7fffffffa4c0) at moc_TagTemplate.cpp:330
#20 0x00007ffff50d5df2 in QMetaObject::activate(QObject*, int, int, void**) ()
   from /usr/lib/libQtCore.so.4
#21 0x00007ffff5c7b50b in QLineEdit::focusOutEvent(QFocusEvent*) () from /usr/lib/libQtGui.so.4
#22 0x00007ffff59000b9 in QWidget::event(QEvent*) () from /usr/lib/libQtGui.so.4
#23 0x00007ffff5c79d44 in QLineEdit::event(QEvent*) () from /usr/lib/libQtGui.so.4
#24 0x00007ffff58b001d in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/lib/libQtGui.so.4
#25 0x00007ffff58b807a in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQtGui.so.4
#26 0x00007ffff50c0c9c in QCoreApplication::notifyInternal(QObject*, QEvent*) ()
   from /usr/lib/libQtCore.so.4
#27 0x00007ffff58b66ef in QApplicationPrivate::setFocusWidget(QWidget*, Qt::FocusReason) ()
   from /usr/lib/libQtGui.so.4
#28 0x00007ffff58fa525 in QWidget::setFocus(Qt::FocusReason) () from /usr/lib/libQtGui.so.4
#29 0x00007ffff58fa807 in QWidget::focusNextPrevChild(bool) () from /usr/lib/libQtGui.so.4
#30 0x00007ffff58fe97d in QWidgetPrivate::hide_helper() () from /usr/lib/libQtGui.so.4
#31 0x00007ffff5905860 in QWidget::setVisible(bool) () from /usr/lib/libQtGui.so.4
#32 0x00007ffff5c51e3d in QDockWidgetLayout::setWidgetForRole(QDockWidgetLayout::Role, QWidget*) ()
   from /usr/lib/libQtGui.so.4
#33 0x000000000043c849 in MDockAncestor::setWidget (this=0xe38080, widget=0x1076bc0)
    at Docks/MDockAncestor.h:13
---Type <return> to continue, or q <return> to quit---
#34 0x0000000000437186 in PropertiesDock::switchToNoUi (this=0xe38080)
    at Docks/PropertiesDock.cpp:470
#35 0x0000000000437b06 in PropertiesDock::switchUi (this=0xe38080) at Docks/PropertiesDock.cpp:378
#36 0x000000000043882a in PropertiesDock::setSelection (this=0xe38080, aFeature=0x0)
    at Docks/PropertiesDock.cpp:225
#37 0x00000000006329eb in MainWindow::on_editPropertiesAction_triggered (this=0x7fffffffd8c0)
    at MainWindow.cpp:698
#38 0x0000000000632519 in MainWindow::on_fileUploadAction_triggered (this=0x7fffffffd8c0)
    at MainWindow.cpp:1082
#39 0x000000000072f277 in MainWindow::qt_metacall (this=0x7fffffffd8c0, 
    _c=QMetaObject::InvokeMetaMethod, _id=26, _a=0x7fffffffb160) at moc_MainWindow.cpp:333
#40 0x00007ffff50d5df2 in QMetaObject::activate(QObject*, int, int, void**) ()
   from /usr/lib/libQtCore.so.4
#41 0x00007ffff58aa147 in QAction::triggered(bool) () from /usr/lib/libQtGui.so.4
#42 0x00007ffff58ab5c0 in QAction::activate(QAction::ActionEvent) () from /usr/lib/libQtGui.so.4
#43 0x00007ffff5c22eda in ?? () from /usr/lib/libQtGui.so.4
#44 0x00007ffff5c23175 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) ()
   from /usr/lib/libQtGui.so.4
#45 0x00007ffff5cf1c2a in QToolButton::mouseReleaseEvent(QMouseEvent*) () from /usr/lib/libQtGui.so.4
#46 0x00007ffff590037f in QWidget::event(QEvent*) () from /usr/lib/libQtGui.so.4
#47 0x00007ffff58b001d in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/lib/libQtGui.so.4
#48 0x00007ffff58b87ca in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQtGui.so.4
#49 0x00007ffff50c0c9c in QCoreApplication::notifyInternal(QObject*, QEvent*) ()
   from /usr/lib/libQtCore.so.4
#50 0x00007ffff58b7a78 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&) () from /usr/lib/libQtGui.so.4
#51 0x00007ffff5920659 in ?? () from /usr/lib/libQtGui.so.4
#52 0x00007ffff591f40f in QApplication::x11ProcessEvent(_XEvent*) () from /usr/lib/libQtGui.so.4
#53 0x00007ffff594776c in ?? () from /usr/lib/libQtGui.so.4
#54 0x00007ffff298213a in g_main_context_dispatch () from /lib/libglib-2.0.so.0
#55 0x00007ffff2985998 in ?? () from /lib/libglib-2.0.so.0
#56 0x00007ffff2985b4c in g_main_context_iteration () from /lib/libglib-2.0.so.0
#57 0x00007ffff50e939c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>)
    () from /usr/lib/libQtCore.so.4
#58 0x00007ffff5946f1f in ?? () from /usr/lib/libQtGui.so.4
#59 0x00007ffff50bf562 in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/libQtCore.so.4
#60 0x00007ffff50bf934 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/libQtCore.so.4
#61 0x00007ffff50c1ba4 in QCoreApplication::exec() () from /usr/lib/libQtCore.so.4
#62 0x0000000000620ee5 in main (argc=1, argv=0x7fffffffe548) at Main.cpp:208

```

**Comment by tomhughes** [comment]
**Author: koying**
**[Added to the original trac issue at 1.09am, Wednesday, 10th February 2010]**

(In [19956]) FIX : Handle case of selection being reset during tag editing (fixes #2646)
