### ISSUE TITLE
Data stats is broken

### ISSUE THREAD

**Issue by tomhughes** [tomhughes/trac-tickets#3112]
**[Submitted to the original trac issue database at 7.56pm, Wednesday, 7th July 2010]**

http://www.openstreetmap.org/stats/data_stats.html

Top users editing over the past...

Exception: failed to allocate memory
/usr/lib/ruby/1.8/generator.rb:102:in `callcc'
/usr/lib/ruby/1.8/generator.rb:102:in `end?'
/usr/lib/ruby/1.8/generator.rb:258:in `each'
/usr/lib/ruby/1.8/generator.rb:257:in `map'
/usr/lib/ruby/1.8/generator.rb:257:in `each'
/usr/lib/ruby/1.8/generator.rb:254:in `loop'
/usr/lib/ruby/1.8/generator.rb:254:in `each'
/home/rails/script/statistics:82
/var/lib/gems/1.8/gems/activerecord-2.3.8/lib/active_record/connection_adapters/abstract/database_statements.rb:136:in `transaction'
/var/lib/gems/1.8/gems/activerecord-2.3.8/lib/active_record/transactions.rb:182:in `transaction_without_deadlock_handling'
/home/rails/vendor/plugins/deadlock_retry/lib/deadlock_retry.rb:46:in `transaction'
/home/rails/script/statistics:18

**Comment by tomhughes** [comment]
**Author: TomH**
**[Added to the original trac issue at 8.03pm, Wednesday, 7th July 2010]**

Yes, memory is a bit tight on that machine at the moment and the stats are low priority so I'm not too worried if they don't work every night.

Once norbert is back up and running I will be look at spreading puff's work out and giving some of it to fuchur and this should resolve itself.

Basically there isn't really a bug here that can be fixed, it's just a temporary operational issue.
