### ISSUE TITLE
segfault in osm2pgsql

### ISSUE THREAD

**Issue by tomhughes** [tomhughes/trac-tickets#3339]
**[Submitted to the original trac issue database at 7.36am, Tuesday, 16th November 2010]**

On mac osx with latest HEAD (r24142) I get:

```

$ gdb osm2pgsql
GNU gdb 6.3.50-20050815 (Apple version gdb-1472) (Wed Jul 21 10:53:12 UTC 2010)
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "x86_64-apple-darwin"...Reading symbols for shared libraries ........... done

(gdb) r -d haiti latest.osm.bz2
Starting program: /usr/local/bin/osm2pgsql -d haiti latest.osm.bz2
Reading symbols for shared libraries .++++++++++............. done
osm2pgsql SVN version 0.70.5

Using projection SRS 900913 (Spherical Mercator)

Program received signal EXC_BAD_ACCESS, Could not access memory.
Reason: KERN_INVALID_ADDRESS at address: 0x000000000000004b
0x00007fff83747050 in __svfscanf_l ()
(gdb) bt
#0  0x00007fff83747050 in __svfscanf_l ()
#1  0x00007fff8374ccb9 in sscanf ()
#2  0x0000000100007210 in read_style_file (filename=0x100019bb8 "/usr/local/share/default.style") at output-pgsql.c:154
#3  0x000000010000755b in pgsql_out_start (options=0x7fff5fbfef20) at output-pgsql.c:1128
#4  0x000000010000cc3a in main (argc=4, argv=0x7fff5fbfeff8) at osm2pgsql.c:508
```

default.style file exists:

```
$ file /usr/local/share/default.style
/usr/local/share/default.style: ASCII English text, with CRLF line terminators
```

**Comment by tomhughes** [comment]
**Author: springmeyer**
**[Added to the original trac issue at 7.39am, Tuesday, 16th November 2010]**

ack, sorry, forgot I had some changes in my local check from trying to get >64 char tags working.
