### ISSUE TITLE
Nominatim DOWN - PostgreSQL server not reachable

### ISSUE THREAD

**Issue by tomhughes** [tomhughes/trac-tickets#3550]
**[Submitted to the original trac issue database at 12.31pm, Tuesday, 22nd February 2011]**

The Nominatim service is down on OpenStreetMap and nominatim.openstreetmap.org. The connection to PostgreSQL cannot be established.

Error message when I searched for something on OSM.org:

Error contacting nominatim.openstreetmap.org: #<RuntimeError: attempted adding second root element to document> /usr/lib/ruby/1.8/rexml/document.rb:92:in `<<' /usr/lib/ruby/1.8/rexml/element.rb:869:in `add' /usr/lib/ruby/1.8/rexml/child.rb:21:in `initialize' /usr/lib/ruby/1.8/rexml/parent.rb:13:in `initialize' /usr/lib/ruby/1.8/rexml/element.rb:59:in `initialize' /usr/lib/ruby/1.8/rexml/element.rb:867:in `new' /usr/lib/ruby/1.8/rexml/element.rb:867:in `add' /usr/lib/ruby/1.8/rexml/element.rb:297:in `add_element' /usr/lib/ruby/1.8/rexml/document.rb:99:in `add_element' /usr/lib/ruby/1.8/rexml/parsers/treeparser.rb:33:in `parse' /usr/lib/ruby/1.8/rexml/document.rb:228:in `build' /usr/lib/ruby/1.8/rexml/document.rb:43:in `initialize' /home/rails/app/controllers/geocoder_controller.rb:404:in `new' /home/rails/app/controllers/geocoder_controller.rb:404:in `fetch_xml' /home/rails/app/controllers/geocoder_controller.rb:237:in `search_osm_nominatim' /var/lib/gems/1.8/gems/actionpack-2.3.8/lib/action_controller/base.rb:1331:in `send' /var/lib/gems/1.8/gems/actionpack-2.3.8/lib/action_controller/base.rb:1331:in `perform_action_without_filters' /var/lib/gems/1.8/gems/actionpack-2.3.8/lib/action_controller/filters.rb:617:in `call_filters' /var/lib/gems/1.8/gems/actionpack-2.3.8/lib/action_controller/filters.rb:610:in `perform_action_without_benchmark' /var/lib/gems/1.8/gems/actionpack-2.3.8/lib/action_controller/benchmarking.rb:68:in `perform_action_without_rescue' /var/lib/gems/1.8/gems/activesupport-2.3.8/lib/active_support/core_ext/benchmark.rb:17:in `ms' /usr/lib/ruby/1.8/benchmark.rb:308:in `realtime' /var/lib/gems/1.8/gems/activesupport-2.3.8/lib/active_support/core_ext/benchmark.rb:17:in `ms' /var/lib/gems/1.8/gems/actionpack-2.3.8/lib/action_controller/benchmarking.rb:68:in `perform_action_without_rescue' /var/lib/gems/1.8/gems/actionpack-2.3.8/lib/action_controller/rescue.rb:160:in `perform_action_without_flash' /var/lib/gems/1.8/gems/actionpack-2.3.8/lib/action_controller/flash.rb:151:in `perform_action' /var/lib/gems/1.8/gems/actionpack-2.3.8/lib/action_controller/base.rb:532:in `send' /var/lib/gems/1.8/gems/actionpack-2.3.8/lib/action_controller/base.rb:532:in `process_without_filters' /var/lib/gems/1.8/gems/actionpack-2.3.8/lib/action_controller/filters.rb:606:in `process' /var/lib/gems/1.8/gems/actionpack-2.3.8/lib/action_controller/base.rb:391:in `process' /var/lib/gems/1.8/gems/actionpack-2.3.8/lib/action_controller/base.rb:386:in `call' /var/lib/gems/1.8/gems/actionpack-2.3.8/lib/action_controller/routing/route_set.rb:438:in `call' /var/lib/gems/1.8/gems/actionpack-2.3.8/lib/action_controller/dispatcher.rb:87:in `dispatch' /var/lib/gems/1.8/gems/actionpack-2.3.8/lib/action_controller/dispatcher.rb:121:in `_call' /var/lib/gems/1.8/gems/actionpack-2.3.8/lib/action_controller/dispatcher.rb:130 /var/lib/gems/1.8/gems/activerecord-2.3.8/lib/active_record/query_cache.rb:29:in `call' /var/lib/gems/1.8/gems/activerecord-2.3.8/lib/active_record/query_cache.rb:29:in `call' /var/lib/gems/1.8/gems/activerecord-2.3.8/lib/active_record/connection_adapters/abstract/query_cache.rb:34:in `cache' /var/lib/gems/1.8/gems/activerecord-2.3.8/lib/active_record/query_cache.rb:9:in `cache' /var/lib/gems/1.8/gems/activerecord-2.3.8/lib/active_record/query_cache.rb:28:in `call' /var/lib/gems/1.8/gems/activerecord-2.3.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:361:in `call' /home/rails/config/initializers/memory_limits.rb:17:in `call' /var/lib/gems/1.8/gems/actionpack-2.3.8/lib/action_controller/string_coercion.rb:25:in `call' /usr/lib/ruby/1.8/rack/head.rb:9:in `call' /usr/lib/ruby/1.8/rack/methodoverride.rb:24:in `call' /var/lib/gems/1.8/gems/actionpack-2.3.8/lib/action_controller/params_parser.rb:15:in `call' /var/lib/gems/1.8/gems/actionpack-2.3.8/lib/action_controller/session/abstract_store.rb:128:in `call' /var/lib/gems/1.8/gems/activesupport-2.3.8/lib/active_support/cache/strategy/local_cache.rb:25:in `call' /var/lib/gems/1.8/gems/actionpack-2.3.8/lib/action_controller/failsafe.rb:26:in `call' /usr/lib/ruby/1.8/rack/lock.rb:11:in `call' /usr/lib/ruby/1.8/rack/lock.rb:11:in `synchronize' /usr/lib/ruby/1.8/rack/lock.rb:11:in `call' /var/lib/gems/1.8/gems/actionpack-2.3.8/lib/action_controller/dispatcher.rb:106:in `call' /usr/lib/ruby/1.8/phusion_passenger/rack/request_handler.rb:96:in `process_request' /usr/lib/ruby/1.8/phusion_passenger/abstract_request_handler.rb:513:in `accept_and_process_next_request' /usr/lib/ruby/1.8/phusion_passenger/abstract_request_handler.rb:274:in `main_loop' /usr/lib/ruby/1.8/phusion_passenger/classic_rails/application_spawner.rb:321:in `start_request_handler' /usr/lib/ruby/1.8/phusion_passenger/classic_rails/application_spawner.rb:275:in `send' /usr/lib/ruby/1.8/phusion_passenger/classic_rails/application_spawner.rb:275:in `handle_spawn_application' /usr/lib/ruby/1.8/phusion_passenger/utils.rb:479:in `safe_fork' /usr/lib/ruby/1.8/phusion_passenger/classic_rails/application_spawner.rb:270:in `handle_spawn_application' /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:357:in `__send__' /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:357:in `server_main_loop' /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:206:in `start_synchronously' /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:180:in `start' /usr/lib/ruby/1.8/phusion_passenger/classic_rails/application_spawner.rb:149:in `start' /usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:219:in `spawn_rails_application' /usr/lib/ruby/1.8/phusion_passenger/abstract_server_collection.rb:132:in `lookup_or_add' /usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:214:in `spawn_rails_application' /usr/lib/ruby/1.8/phusion_passenger/abstract_server_collection.rb:82:in `synchronize' /usr/lib/ruby/1.8/phusion_passenger/abstract_server_collection.rb:79:in `synchronize' /usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:213:in `spawn_rails_application' /usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:132:in `spawn_application' /usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:275:in `handle_spawn_application' /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:357:in `__send__' /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:357:in `server_main_loop' /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:206:in `start_synchronously' /usr/share/phusion-passenger/helper-scripts/passenger-spawn-server:99 ... attempted adding second root element to document Line: Position: Last 80 unconsumed characters: function.pg-connect</a>]: Unable to connect to PostgreSQL server: could not conne

**Comment by tomhughes** [comment]
**Author: guerda**
**[Added to the original trac issue at 3.17pm, Tuesday, 22nd February 2011]**

Is running again.
