### ISSUE TITLE
Corrupted data after merging nodes

### ISSUE THREAD

**Issue by tomhughes** [tomhughes/trac-tickets#3690]
**[Submitted to the original trac issue database at 11.51am, Friday, 15th April 2011]**

I have created a simple example. To reproduce the error do the following:
1.) Open before.osm
2.) Select the the middle point of the top most way (keep mouse button pressed)
3.) Press CTRL and darg the node over the middle point of the second way.
4.) Drop the node -> Both nodes are merged.
5.) Press 'j' to join the new node with the third way. 

The result is the error message below. I have saves the result also as after.osm.

IMPORTANT: Do not deselect before pressing 'j'.

It looks like the selection is not correct after merging with CTRL + drag&drop.

Repository Root: http://josm.openstreetmap.de/svn
Build-Date: 2011-04-14 01:31:50
Last Changed Author: bastiK
Revision: 4021
Repository UUID: 0c6e7542-c601-0410-84e7-c038aed88b3b
URL: http://josm.openstreetmap.de/svn/trunk
Last Changed Date: 2011-04-13 22:43:46 +0200 (Wed, 13 Apr 2011)
Last Changed Rev: 4021

Identification: JOSM/1.5 (4021 de)
Memory Usage: 59 MB / 494 MB (15 MB allocated, but free)
Java version: 1.6.0_24, Sun Microsystems Inc., Java HotSpot(TM) Client VM
Operating system: Windows XP

Dataset consistency test:
[DELETED REFERENCED] {Way id=-32 version=0 MV nodes=[{Node id=-33 version=0 MV lat=0.8903012061942707,lon=-2.572852888038059}, {Node id=-34 version=0 MVD lat=0.851796310595745,lon=-1.8437515447456738}, {Node id=-26 version=0 MV lat=0.8496262927567253,lon=-1.8425458463810516}, {Node id=-35 version=0 MV lat=0.8591026876126888,lon=-1.1122388047240452}]} refers to deleted primitive {Node id=-34 version=0 MVD lat=0.851796310595745,lon=-1.8437515447456738}

Plugin: buildings_tools (25469)
Plugin: contourmerge (25626)
Plugin: graphview (25199)
Plugin: measurement (25199)
Plugin: openstreetbugs (25664)
Plugin: public_transport (25192)
Plugin: reverter (25578)
Plugin: routes (25199)
Plugin: routing (25843)
Plugin: terracer (25199)
Plugin: turnrestrictions (25845)
Plugin: undelete (25199)
Plugin: utilsplugin2 (25817)

org.openstreetmap.josm.data.osm.DataIntegrityProblemException: Deleted node referenced: {Way id=-32 version=0 MV nodes=[{Node id=-33 version=0 MV lat=0.8903012061942707,lon=-2.572852888038059}, {Node id=-34 version=0 MVD lat=0.851796310595745,lon=-1.8437515447456738}, {Node id=-26 version=0 MV lat=0.8496262927567253,lon=-1.8425458463810516}, {Node id=-35 version=0 MV lat=0.8591026876126888,lon=-1.1122388047240452}]}
	at org.openstreetmap.josm.data.osm.Way.checkNodes(Way.java:444)
	at org.openstreetmap.josm.data.osm.Way.fireNodesChanged(Way.java:456)
	at org.openstreetmap.josm.data.osm.Way.setNodes(Way.java:65)
	at org.openstreetmap.josm.data.osm.Way.cloneFrom(Way.java:232)
	at org.openstreetmap.josm.command.ChangeCommand.executeCommand(ChangeCommand.java:43)
	at org.openstreetmap.josm.command.SequenceCommand.executeCommand(SequenceCommand.java:53)
	at org.openstreetmap.josm.data.UndoRedoHandler.addNoRedraw(UndoRedoHandler.java:36)
	at org.openstreetmap.josm.data.UndoRedoHandler.add(UndoRedoHandler.java:58)
	at org.openstreetmap.josm.actions.JoinNodeWayAction.actionPerformed(JoinNodeWayAction.java:85)
	at javax.swing.SwingUtilities.notifyAction(Unknown Source)
	at javax.swing.JComponent.processKeyBinding(Unknown Source)
	at javax.swing.KeyboardManager.fireBinding(Unknown Source)
	at javax.swing.KeyboardManager.fireKeyboardAction(Unknown Source)
	at javax.swing.JComponent.processKeyBindingsForAllComponents(Unknown Source)
	at javax.swing.JComponent.processKeyBindings(Unknown Source)
	at javax.swing.JComponent.processKeyEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.KeyboardFocusManager.redispatchEvent(Unknown Source)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(Unknown Source)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(Unknown Source)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(Unknown Source)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$000(Unknown Source)
	at java.awt.EventQueue$1.run(Unknown Source)
	at java.awt.EventQueue$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(Unknown Source)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$2.run(Unknown Source)
	at java.awt.EventQueue$2.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by tomhughes** [comment]
**Author: mdk**
**[Added to the original trac issue at 11.58am, Friday, 15th April 2011]**

Sorry, wrong system. I open the same bug in http://josm.openstreetmap.de/newticket.

mdk
