### ISSUE TITLE
Java error in tah client

### ISSUE THREAD

**Issue by tomhughes** [tomhughes/trac-tickets#4154]
**[Submitted to the original trac issue database at 8.29pm, Wednesday, 21st December 2011]**

Trying to render Tileset (12,2151,1411) I get following error message. Seems to be a problem in Java code:
```
[#13   0% tile] Running area-center... ERROR                                
  The following command produced an error message:
  java -Xmx1536M -cp java/osmosis/osmosis.jar:java/area-center.jar com.bretth.osmosis.core.Osmosis -q -p org.tah.areaCenter.AreaCenterPlugin --read-xml /tmp/tah1/12_2151_1411_7dEpx/dataclose-areas.osm --area-center --write-xml /tmp/tah1/12_2151_1411_7dEpx/dataclose-areas-area-center.osm
  Debug output follows:
  | Dec 21, 2011 6:11:32 PM com.bretth.osmosis.core.xml.v0_5.impl.OsmElementProcessor begin
  | WARNING: Expected version 0.5 but received 0.6.
  | Dec 21, 2011 6:11:36 PM com.bretth.osmosis.core.pipeline.common.ActiveTaskManager waitForCompletion
  | SEVERE: Thread for task 1-read-xml failed
  | com.bretth.osmosis.core.OsmosisRuntimeException: Cannot represent 3415937211 as an integer.
  |     at com.bretth.osmosis.core.util.LongAsInt.longToInt(LongAsInt.java:33)
  |     at com.bretth.osmosis.core.domain.v0_5.WayNode.<init>(WayNode.java:28)
  |     at com.bretth.osmosis.core.xml.v0_5.impl.WayNodeElementProcessor.begin(WayNodeElementProcessor.java:45)
  |     at com.bretth.osmosis.core.xml.v0_5.impl.OsmHandler.startElement(OsmHandler.java:92)
  |     at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:504)
  |     at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:182)
...
```

**Comment by tomhughes** [comment]
**Author: iandees**
**[Added to the original trac issue at 8.54pm, Monday, 9th September 2013]**

Cleaning aging tickets.
