### ISSUE TITLE
Segfault in slim mode

### ISSUE THREAD

**Issue by tomhughes** [tomhughes/trac-tickets#4717]
**[Submitted to the original trac issue database at 2.09pm, Wednesday, 12th December 2012]**

While running osm2pgsql in ubuntu 12.04 to import Japan.osm.bz2 I am getting a segfault in slim mode, while running the same in a non slim mode there is no segfault . 

----
osm2pgsql version :  Current SVN 0.80.0 (32bit id space)[[BR]]

Postgis version : 2.0.1-2~precise3[[BR]]

Postgres version : 9.1.6-0ubuntu12.04.1[[BR]]

----
Back trace in GDB :

#0  addItem (head=0x7fffffffe820, name=0x7fffffffe850 "w41890520", value=0x46af260 "inner", noDupe=<optimized out>) at keyvals.c:262
#1  0x000000000041048f in pgsql_rels_set (id=5741, members=<optimized out>, member_count=6, tags=0x62c3d8) at middle-pgsql.c:939
#2  0x000000000040c4c8 in pgsql_add_relation (id=5741, members=0x46818d0, member_count=6, tags=0x62c3d8) at output-pgsql.c:1749
#3  0x0000000000414879 in EndElement (name=0x62c3d8 "", osmdata=0x62c380) at parse-xml2.c:298
#4  0x0000000000414a14 in processNode (osmdata=0x62c380, reader=0x46a57d0) at parse-xml2.c:358
#5  streamFileXML2 (filename=0x7fffffffeeb3 "japan.osm.bz2", sanitize=<optimized out>, osmdata=0x62c380) at parse-xml2.c:383
#6  0x0000000000404dd3 in main (argc=9, argv=0x7fffffffec78) at osm2pgsql.c:683

----
Crash statement : 
Processing: Node(82078k 91.6k/s) Way(7043k 6.63k/s) Relation(0 0.00/s)
Program received signal SIGSEGV, Segmentation fault.
addItem (head=0x7fffffffe820, name=0x7fffffffe850 "w41890520", value=0x46af260 "inner", noDupe=<optimized out>) at keyvals.c:262
262         head->next->prev = item;

**Comment by tomhughes** [comment]
**Author: amm**
**[Added to the original trac issue at 4.47pm, Saturday, 12th January 2013]**

Could you try and see if this also occurs with a fresh svn checkout of osm2pgsql?

**Comment by tomhughes** [comment]
**Author: pnorman**
**[Added to the original trac issue at 10.20am, Tuesday, 3rd January 2017]**

No reply from the user, and the bug was reported against a five year old version.
