### ISSUE TITLE
OperationalError: database is locked

### ISSUE THREAD

**Issue by tomhughes** [tomhughes/trac-tickets#4803]
**[Submitted to the original trac issue database at 4.32pm, Sunday, 3rd March 2013]**

==== How to Reproduce ====

While doing a GET operation on `/query`, Trac issued an internal error.

*(please provide additional details here)*

Just did try to open three component queries in three different tabs. First succeeded other two gave error

Request parameters:
```
{'component': u'wiki',
 'order': u'priority',
 'status': [u'new', u'assigned', u'reopened']}
```

User agent: `#USER_AGENT#`

==== System Information ====
*System information not available*

==== Enabled Plugins ====
*Plugin information not available*

==== Python Traceback ====
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/trac/web/main.py", line 511, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.7/dist-packages/trac/web/main.py", line 260, in dispatch
    req.session.save()
  File "/usr/lib/python2.7/dist-packages/trac/web/session.py", line 105, in save
    @self.env.with_transaction()
  File "/usr/lib/python2.7/dist-packages/trac/db/api.py", line 77, in transaction_wrapper
    fn(ldb)
  File "/usr/lib/python2.7/dist-packages/trac/web/session.py", line 140, in save_session
    """, (self.sid, authenticated))
  File "/usr/lib/python2.7/dist-packages/trac/db/util.py", line 65, in execute
    return self.cursor.execute(sql_escape_percent(sql), args)
  File "/usr/lib/python2.7/dist-packages/trac/db/sqlite_backend.py", line 78, in execute
    result = PyFormatCursor.execute(self, *args)
  File "/usr/lib/python2.7/dist-packages/trac/db/sqlite_backend.py", line 56, in execute
    args or [])
  File "/usr/lib/python2.7/dist-packages/trac/db/sqlite_backend.py", line 48, in _rollback_on_error
    return function(self, *args, **kwargs)
OperationalError: database is locked
```

**Comment by tomhughes** [comment]
**Author: TomH**
**[Added to the original trac issue at 4.38pm, Sunday, 3rd March 2013]**

This is an unfortunate fact of life with trac using the sqlite database - if somebody else is doing something that locks the database for a period then you can get a "database locked" error.

Not a lot I can do about it I'm afraid.
