### ISSUE TITLE
ogr2osm dose not regonize newÄºy build gdal

### ISSUE THREAD

**Issue by tomhughes** [tomhughes/trac-tickets#4932]
**[Submitted to the original trac issue database at 5.18pm, Monday, 5th August 2013]**

joni@mpi1:~/src/ogr2osm$ python ogr2osm.py ~MAP*/M5132R.xml -t road.py
Traceback (most recent call last):
  File "ogr2osm.py", line 59, in <module>
    from osgeo import ogr
  File "/usr/local/lib/python2.7/dist-packages/osgeo/__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/osgeo/__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
ImportError: /usr/local/lib/libgdal.so.1: undefined symbol: GEOSGeom_getCoordinateDimension
joni@mpi1:~/src/ogr2osm$ 

due server installation ubuntu 12.4 gdal standard library is at machine and
new gdal was build to read MTK-GDE format file's.

**Comment by tomhughes** [comment]
**Author: pnorman**
**[Added to the original trac issue at 5.57pm, Monday, 9th September 2013]**

ogr2osm is now hosted at https://github.com/pnorman/ogr2osm, tickets should be opened there if still valid. 

This looks like an issue with your gdal install anyways, not an ogr2osm issue.
