### ISSUE TITLE
Internal server error 500 when fetching large changesets

### ISSUE THREAD

**Issue by tomhughes** [tomhughes/trac-tickets#5247]
**[Submitted to the original trac issue database at 12.50pm, Thursday, 20th November 2014]**

**What steps will reproduce the problem?**

Start JOSM 
Open reverter plugin
Insert changeset 26757923
Wait up to 15 (or more) minutes since there is a lot of data

**What is the expected result?**

Should successfully download past changeset data without warning messages.

**What happens instead?**

A error message appears in roughly half of the attempts and every time at different points. 

It is always a 500 Internal Server Error.

'''If any option is chosen an error message appears stating it's not possible to complete the request.
Please provide any additional information below. Attach a screenshot if possible.'''

```
Revision: 7723
Repository Root: http://josm.openstreetmap.de/svn
Relative URL: ^/trunk
Last Changed Author: Klumbumbus
Last Changed Date: 2014-11-12 22:45:27 +0100 (Wed, 12 Nov 2014)
Build-Date: 2014-11-13 02:34:10
URL: http://josm.openstreetmap.de/svn/trunk
Repository UUID: 0c6e7542-c601-0410-84e7-c038aed88b3b
Last Changed Rev: 7723

Identification: JOSM/1.5 (7723 pt) Windows 7 64-Bit
Memory Usage: 491 MB / 1820 MB (178 MB allocated, but free)
Java version: 1.8.0_25, Oracle Corporation, Java HotSpot(TM) 64-Bit Server VM
Dataset consistency test: No problems found

Plugins:
- FastDraw (30762)
- OpeningHoursEditor (30737)
- PicLayer (30762)
- RoadSigns (30788)
- alignways (30695)
- buildings_tools (30762)
- download_along (30762)
- geotools (30762)
- imagery_offset_db (30808)
- jts (30762)
- measurement (30737)
- opendata (30806)
- public_transport (30762)
- reverter (30737)
- routes (30762)
- undelete (30762)
- utilsplugin2 (30762)

Last errors/warnings:
- E: Modelo de etiquetas com erros "place-Localidade" - o nmero de itens em 'display_values' tem de ser igual ao nmero de 'values'
- E: Modelo de etiquetas com erros "note-Tipo de povoado" - o nmero de itens em 'display_values' tem de ser igual ao nmero de 'values'
- E: org.openstreetmap.josm.io.OsmTransferException: org.openstreetmap.josm.io.OsmApiException: ResponseCode=500, Error Body=<<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
- E: org.openstreetmap.josm.io.OsmTransferException: org.openstreetmap.josm.io.OsmApiException: ResponseCode=500, Error Body=<<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">

org.openstreetmap.josm.io.OsmTransferException: org.openstreetmap.josm.io.OsmApiException: ResponseCode=500, Error Body=<<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at 
 webmaster@openstreetmap.org to inform them of the time this error occurred,
 and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
<hr>
<address>Apache/2.4.7 (Ubuntu) Server at api.openstreetmap.org Port 443</address>
</body></html>>
	at reverter.OsmServerMultiObjectReader.readObject(OsmServerMultiObjectReader.java:34)
	at reverter.OsmServerMultiObjectReader.readObject(OsmServerMultiObjectReader.java:20)
	at reverter.ChangesetReverter.readObjectVersion(ChangesetReverter.java:190)
	at reverter.ChangesetReverter.downloadObjectsHistory(ChangesetReverter.java:223)
	at reverter.RevertChangesetTask.realRun(RevertChangesetTask.java:100)
	at org.openstreetmap.josm.gui.PleaseWaitRunnable.doRealRun(PleaseWaitRunnable.java:93)
	at org.openstreetmap.josm.gui.PleaseWaitRunnable.run(PleaseWaitRunnable.java:161)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.openstreetmap.josm.io.OsmApiException: ResponseCode=500, Error Body=<<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at 
 webmaster@openstreetmap.org to inform them of the time this error occurred,
 and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
<hr>
<address>Apache/2.4.7 (Ubuntu) Server at api.openstreetmap.org Port 443</address>
</body></html>>
	at org.openstreetmap.josm.io.OsmServerReader.getInputStreamRaw(OsmServerReader.java:194)
	at org.openstreetmap.josm.io.OsmServerReader.getInputStreamRaw(OsmServerReader.java:104)
	at org.openstreetmap.josm.io.OsmServerReader.getInputStream(OsmServerReader.java:68)
	at org.openstreetmap.josm.io.OsmServerReader.getInputStream(OsmServerReader.java:51)
	at reverter.OsmServerMultiObjectReader.readObject(OsmServerMultiObjectReader.java:31)
	... 11 more
```

**Comment by tomhughes** [comment]
**Author: TomH**
**[Added to the original trac issue at 1.17pm, Thursday, 20th November 2014]**

This is (unfortunately) normal currently - they are just too big and complicated and in order to protect server resources we have a timeout in place which is what you are seeing.

Hopefully one day the relation/full call will be moved into cgimap and we'll be able to handle larger relations.

**Comment by tomhughes** [comment]
**Author: ViriatoLusitano**
**[Added to the original trac issue at 1.53pm, Thursday, 20th November 2014]**

I see, should this ticket be closed since it's an already known issue?

**Comment by tomhughes** [comment]
**Author: TomH**
**[Added to the original trac issue at 2.16pm, Thursday, 20th November 2014]**

Well there are probably other tickets covering it, yes.

**Comment by tomhughes** [comment]
**Author: don-vip**
**[Added to the original trac issue at 2.21pm, Thursday, 20th November 2014]**

Replying to [comment:4 TomH]:
> Well there are probably other tickets covering it, yes.

Yep, #4692 I think.

**Comment by tomhughes** [comment]
**Author: pnorman**
**[Added to the original trac issue at 4.28pm, Thursday, 20th November 2014]**

> Hopefully one day the relation/full call will be moved into cgimap and we'll be able to handle larger relations.

relation/full is in cgimap, TomH presumably means the changeset download API call.

**Comment by tomhughes** [comment]
**Author: TomH**
**[Added to the original trac issue at 4.29pm, Thursday, 20th November 2014]**

Oh sorry, yes, whatever call this is ;-)

**Comment by tomhughes** [comment]
**Author: bastik**
**[Added to the original trac issue at 9.57am, Friday, 21st November 2014]**

It's an invitation to upload "unwanted" stuff and give people who have to fix it a hard time. What would be the solution when this happens?

Maybe restrict the number of objects in one changeset to what can still be downloaded with `/changeset/#id/download`. Or add a call to split the download into several requests (like `/trackpoints?bbox=left,bottom,right,top&page=X`)
