### ISSUE TITLE
osmosis fails on debian with error about Fileformat$BlobHeader

### ISSUE THREAD

**Issue by tomhughes** [tomhughes/trac-tickets#5414]
**[Submitted to the original trac issue database at 8.49pm, Tuesday, 30th August 2016]**

I'm running osmosis on debian (sid).  I just upgraded to 0.45-3.  Also installed are

libosmpbf-java 1.3.3-6
libprotobuf-java 2.6.1-1.3

Running OpenJDK 1.8.0_77-Debian.  Debian appears to apply a hefty size patch to Fileformat.java.  It's deep in the .pc directory.

Here's the error.

Aug 30, 2016 3:50:13 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Osmosis Version 0.45
Aug 30, 2016 3:50:14 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Preparing pipeline.
Aug 30, 2016 3:50:14 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Launching pipeline execution.
Aug 30, 2016 3:50:14 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Pipeline executing, waiting for completion.
Aug 30, 2016 3:50:14 PM org.openstreetmap.osmosis.core.pipeline.common.ActiveTaskManager waitForCompletion
SEVERE: Thread for task 1-read-pbf failed
java.lang.NoSuchMethodError: org.openstreetmap.osmosis.osmbinary.Fileformat$BlobHeader.makeImmutable()V
        at org.openstreetmap.osmosis.osmbinary.Fileformat$BlobHeader.<clinit>(Fileformat.java:1347)
        at org.openstreetmap.osmosis.osmbinary.file.FileBlockHead.readHead(FileBlockHead.java:57)
        at org.openstreetmap.osmosis.osmbinary.file.FileBlock.process(FileBlock.java:130)
        at org.openstreetmap.osmosis.osmbinary.file.BlockInputStream.process(BlockInputStream.java:34)
        at crosby.binary.osmosis.OsmosisReader.run(OsmosisReader.java:45)
        at java.lang.Thread.run(Thread.java:745)

Aug 30, 2016 3:50:14 PM org.openstreetmap.osmosis.core.Osmosis main
SEVERE: Execution aborted.
org.openstreetmap.osmosis.core.OsmosisRuntimeException: One or more tasks failed.
        at org.openstreetmap.osmosis.core.pipeline.common.Pipeline.waitForCompletion(Pipeline.java:146)
        at org.openstreetmap.osmosis.core.Osmosis.run(Osmosis.java:92)
        at org.openstreetmap.osmosis.core.Osmosis.main(Osmosis.java:37)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:328)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:408)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:351)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:31)

**Comment by tomhughes** [comment]
**Author: brett@bretth.com**
**[Added to the original trac issue at 10.17am, Monday, 12th September 2016]**

Any Debian issues are probably best raised via Debian support channels.

However I'm hoping that this issue is already addressed.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=835776
https://github.com/openstreetmap/osmosis/pull/32
